### PR TITLE
python -m rawdisk

### PR DESCRIPTION
**Pull request by techtonik**

### CODE REVIEW

**Comment by dariusbakunas** [comment]
main.py already has this capability, you can just do python -m rawdisk.main, but preferred way is to just use command line utility that is installed (`rawdisk --help`) when rawdisk package is installed

**Comment by techtonik** [comment]
@dariusbakunas `python -m rawdisk.main` is a non-standard way to run Python modules. Why install the package if you can just run it from source? It is not C.

**Comment by dariusbakunas** [comment]
Not sure I understand your comment, are you suggesting that everyone would have to checkout this repo to run it? instead of just doing `pip install rawdisk` ? or how is `python -m rawdisk` different from `python -m rawdisk.main` ? not sure what would be the benefit of this pr

**Comment by techtonik** [comment]
I've got several Python versions installed, and `pip install rawdisk` doesn't guarantee that it will be installed into Python 3.5 and not for some other python version. In fact, I even run pip as `python -m pip` using Python that is needed for the job at hand.

**Comment by techtonik** [comment]
I need to check, but there is a chance that `main.py` can just be renamed to `__main__.py`

**Comment by dariusbakunas** [comment]
are you aware about python virtual environments?

**Comment by techtonik** [comment]
Yes. https://github.com/pypa/virtualenv/commits?author=techtonik

**Comment by dariusbakunas** [comment]
Ok, then I don't understand the problem :)

**Comment by techtonik** [comment]
The problem is that there are automated tools that can run Python packages and libs, and those tools are unable to determine that the correct command to run your package is `blablabla.main` instead of `blablabla`. Python standard API is to provide `blablabla.__main__` as an entrypoint for package that can be executed,

**Comment by techtonik** [comment]
You command line script is not the API. It will end in different directories on Linux and Windows. It will depend on whatever Python distribution you were using. `python -m <package>` is the more portable way to run code that has no reasons to abandon such simple use case.

**Pull request closed without merging**
